### ISSUE TITLE
Rearrange id after deletion

### ISSUE THREAD

**Issue by gustavofsousa** [gustavofsousa/Book-Library#1]
When I delete a book, in that ID is a gap before the next one. e.g.:
1- Book, Author
3- AnotherBook, anotherAuthor

Idea: Do some update_id_seqence function. Need to see if its the best approach.

**Comment by AWDev489** [comment]
Hey there, i have an idea for the "update_id_sequence" function. If you dont mind, i would try :)

**Comment by gustavofsousa** [comment]
@AWDev489 Feel free to give your try!
